//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChandedRecord
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int PatientId { get; set; }
        public int DoctorId { get; set; }
        public string Patient_Diognosis { get; set; }
        public string Current_Prescription { get; set; }
        public string Previous_presciption { get; set; }
        public System.DateTime Date_of_Prescription { get; set; }
        public Nullable<int> Hospital_ID { get; set; }
    
        public virtual Record Record { get; set; }
        public virtual Hospital Hospital { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
