//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChemistView
    {
        public int Id { get; set; }
        public string Patient_Name { get; set; }
        public string Current_Prescription { get; set; }
        public string Previous_presciption { get; set; }
        public System.DateTime Date_of_Prescription { get; set; }
        public string Dr_Name { get; set; }
    }
}
