//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctores_More_Details
    {
        public int Patient_ID { get; set; }
        public string Patient_name { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string Medical_History { get; set; }
        public string Other { get; set; }
        public string Patient_Diognosis { get; set; }
        public string Current_Prescription { get; set; }
        public string Previous_presciption { get; set; }
        public string Dr_name { get; set; }
    }
}
