//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int RecordId { get; set; }
        public int DoctorId { get; set; }
        public System.DateTime LogTime { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Record Record { get; set; }
    }
}
