//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regestration_date
    {
        public int Id { get; set; }
        public Nullable<int> PatientId { get; set; }
        public System.DateTime Regestration_date1 { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
