//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Link.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<int> Attendant { get; set; }
        public string Blood_type { get; set; }
        public int Quantity { get; set; }
    }
}
